language: android

android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support
script:
  - ./gradlew :yodian_app:assemblePreview
after_success:
    - fir p app/build/outputs/apk/yodian_app-preview.apk -T 39795a5d8682393820e55dcf750809f6
notifications:
  recipients:
    - 1091041307@qq.com
    - 1923873@qq.com

sudo: false