package maimeng.yodian.app.client.android.common;

/**
 * Created by apple on 15/11/23.
 */
public class UEvent {
    public static final String AUTH_SMS = "yd001";//登录-短信注册申请
    public static final String AUTH_SMS_SUCESS = "yd002";//登录-短信注册成功
    public static final String AUTH_SINA = "yd003";//登录-微博登录
    public static final String AUTH_SINA_SUCESS = "yd004";//登录-微博登录成功
    public static final String AUTH_WECHAT = "yd005";//登录-微信登录
    public static final String AUTH_WECHAT_SUCESS = "yd006";//登录-微信登录成功
    public static final String INDEX= "yd007";//精选页
    public static final String HOME = "yd008";//我的页
    public static final String SKILL_DETIAL = "yd009";//技能详情页
    public static final String SKILL_PUBLISH = "yd010";//技能发布页
    public static final String RMARK_PUBLISH= "yd011";//技能日记发布页
    public static final String ENTRY_HOME_FROM_INDEX = "yd012";//精选页－我的页入口点击
    public static final String ENTRY_INDEX_FROM_HOME = "yd013";//我的页－精选页入口点击
    public static final String EDIT_BASIC_INFO_FROM_HOME = "yd014";//我的页－我的信息编辑点击
    public static final String SETTING_SYSTEM_FROM_HOME = "yd015";//我的页－系统设置点击
    public static final String PUBLISH_SKILL_FROM_HOME = "yd016";//我的页－发布技能点击
    public static final String SKILL_SHARE = "yd017";//技能分享点击
    public static final String SKILL_SHARE_WECHAT = "yd018";//技能分享－微信好友点击
    public static final String SKILL_SHARE_WECHAT_SUCESS = "yd019";//技能分享－微信好友成功
    public static final String SKILL_SHARE_FRIENDS= "yd020";//技能分享－朋友圈点击
    public static final String SKILL_SHARE_FRIENDS_SUCESS = "yd021";//技能分享－朋友圈成功
    public static final String SKILL_SHARE_SINA= "yd022";//技能分享－微博点击
    public static final String SKILL_SHARE_SINA_SUCESS= "yd023";//技能分享－微博成功
    public static final String SKILL_SHARE_QQ = "yd024";//技能分享－qq点击
    public static final String SKILL_SHARE_QQ_SUCESS = "yd025";//技能分享－qq成功
    public static final String EDIT_SKILL = "yd026";//技能编辑点击
    public static final String EDIT_SKILL_MODIFY = "yd027";//技能编辑－修改点击
    public static final String EDIT_SKILL_UP_DOWN = "yd028";//技能编辑－上下架点击
    public static final String EDIT_SKILL_DELETE = "yd029";//技能编辑－删除点击
    public static final String CONTACT_TA = "yd030";//联系ta点击
    public static final String CONTACT_TA_WECHAT= "yd031";//联系ta－打开微信点击
    public static final String SKILL_DETAIL_PUBLISH_RMARK = "yd032";//技能详情页－发布日记点击
    public static final String TEMPLATE_SKILL= "yd033";//发布技能模版页
    public static final String TEMPLATE_SKILL_FIRST = "yd034";//发布技能模版页－模版1
    public static final String TEMPLATE_SKILL_SECOND= "yd035";//发布技能模版页－模版2
    public static final String TEMPLATE_SKILL_THIRD = "yd036";//发布技能模版页－模版3
    public static final String TEMPLATE_SKILL_FOURTH = "yd037";//发布技能模版页－模版4
    public static final String TEMPLATE_SKILL_FIFTH = "yd038";//发布技能模版页－模版5
    public static final String TEMPLATE_SKILL_DEFINE = "yd039";//发布技能模版页－自定义模版
    public static final String RMARK_DELETE = "yd040";//技能日记删除点击
    public static final String SMS_LOG_REG = "yd041";//消息列表页
    public static final String SMS_LOG_REG = "yd042";//消息聊天界面页
    public static final String SMS_LOG_REG = "yd043";//消息聊天界面页－发送名片
    public static final String SMS_LOG_REG = "yd044";//消息聊天界面页－查看技能
    public static final String SMS_LOG_REG = "yd045";//精选页－分类菜单点击
    public static final String SMS_LOG_REG = "yd046";//banner1
    public static final String SMS_LOG_REG = "yd047";//banner2
    public static final String SMS_LOG_REG = "yd048";//banner3
    public static final String SMS_LOG_REG = "yd049";//banner4
    public static final String SMS_LOG_REG = "yd050";//推荐技能位
    public static final String SMS_LOG_REG = "yd051";//_推荐用户位
    public static final String SMS_LOG_REG = "yd052";//IM_右上角微信点击
    public static final String SMS_LOG_REG = "yd053";//日记发布页—提交点击
    public static final String SMS_LOG_REG = "yd054";//编辑技能—技能预览页
    public static final String SMS_LOG_REG = "yd055";//我的余额—已提现金额页
    public static final String SMS_LOG_REG = "yd056";//已出售订单—接单、发货
    public static final String SMS_LOG_REG = "yd057";//订单详情—接单、发货
    public static final String SMS_LOG_REG = "yd058";//已购买订单—付款、确认收货
    public static final String SMS_LOG_REG = "yd059";//订单详情—付款、确认收货
    public static final String SMS_LOG_REG = "yd060";//主页-点击购买技能
    public static final String SMS_LOG_REG = "yd061";//支付方式-微信支付
    public static final String SMS_LOG_REG = "yd062";//支付方式—支付宝支付
    public static final String SMS_LOG_REG = "yd063";//支付方式—余额支付
    public static final String SMS_LOG_REG = "yd064";//点击购买技能-微信支付、支付宝支付、余额支付
    public static final String SMS_LOG_REG = "yd065";//绑定银行卡页
    public static final String SMS_LOG_REG = "yd066";//申请绑定银行卡-提交
    public static final String SMS_LOG_REG = "yd067";//申请担保交易页
    public static final String SMS_LOG_REG = "yd068";//申请担保交易功能-提交
    public static final String SMS_LOG_REG = "yd069";//我的余额-余额-提现点击
    public static final String SMS_LOG_REG = "yd070";//添加技能-开启在线支付
    public static final String SMS_LOG_REG = "yd071";//编辑技能-修改-开启在线支付
    public static final String SMS_LOG_REG = "yd072";//编辑技能-修改-关闭在线支付
    public static final String SMS_LOG_REG = "yd073";//技能详情-点击购买技能
    public static final String SMS_LOG_REG = "yd074";//认证信息的入口
    public static final String SMS_LOG_REG = "yd075";//认证信息-手机获取验证码
    public static final String SMS_LOG_REG = "yd076";//认证信息-提交
    public static final String SMS_LOG_REG = "yd077";//认证信息-取消
    public static final String SMS_LOG_REG = "yd078";//支付宝信息页的入口
    public static final String SMS_LOG_REG = "yd079";//支付宝信息页的取消
    public static final String SMS_LOG_REG = "yd080";//支付宝信息页的提交
    public static final String SMS_LOG_REG = "yd081";//订单详情-右上角-取消订单
    public static final String SMS_LOG_REG = "yd082";//订单详情-右上角-取消订单-确定取消
    public static final String SMS_LOG_REG = "yd083";//订单详情-右上角-取消订单-不取消
    public static final String SMS_LOG_REG = "yd084";//浮层广告１的点击次数
    public static final String SMS_LOG_REG = "yd085";//浮层广告２的点击次数
    public static final String SMS_LOG_REG = "yd086";//浮层广告3的点击次数
    public static final String SMS_LOG_REG = "yd087";//开通在线支付-绑定填写信息-是
    public static final String SMS_LOG_REG = "yd088";//开通在线支付-绑定填写信息-否
    public static final String SMS_LOG_REG = "yd089";//购买技能-支付方式（wx、alipay）-使用余额抵扣-是
    public static final String SMS_LOG_REG = "yd090";//购买技能-支付方式（wx、alipay）-使用余额抵扣-否
    public static final String SMS_LOG_REG = "yd091";//首页-分类1
    public static final String SMS_LOG_REG = "yd092";//首页-分类２
    public static final String SMS_LOG_REG = "yd093";//首页-分类３
    public static final String SMS_LOG_REG = "yd094";//首页-分类４
    public static final String SMS_LOG_REG = "yd095";//首页-分类５
    public static final String SMS_LOG_REG = "yd096";//首页-分类６
    public static final String SMS_LOG_REG = "yd097";//首页-分类７
    public static final String SMS_LOG_REG = "yd098";//首页-分类８
    public static final String SMS_LOG_REG = "yd099";//首页-分类９
    public static final String SMS_LOG_REG = "yd100";//首页-分类１０
    public static final String SMS_LOG_REG = "yd101";//首页-分类1１
    public static final String SMS_LOG_REG = "yd102";//首页-分类1２
    public static final String SMS_LOG_REG = "yd103";//首页-分类1３
    public static final String SMS_LOG_REG = "yd104";//首页-分类1４
    public static final String SMS_LOG_REG = "yd105";//首页-分类15
    public static final String SMS_LOG_REG = "yd106";//抽奖活动技能-技能详情-顶部倒计时模块-点击
    public static final String SMS_LOG_REG = "yd107";//购买完成-抽奖-去抽奖
    public static final String SMS_LOG_REG = "yd108";//购买完成-抽奖-放弃抽奖
    public static final String SMS_LOG_REG = "yd109";//浮层广告-1-展示
    public static final String SMS_LOG_REG = "yd110";//浮层广告-2-展示
    public static final String SMS_LOG_REG = "yd111";//浮层广告-３－展示

}
